load("//tools:build.bzl", "cc_test")
load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

#cc_library(
#name = "config",
#hdrs = [
#"base_config.h",
#],
#deps = [
#":abstract_config",
#"//src/util",
#"@com_google_absl//absl/synchronization",
#],
#)

#cc_test(
#name = "config_test",
#srcs = ["config_test.cc"],
#data = [
#"//test_data/config_test:base_config.json",
#],
#deps = [
#":config",
#"//src/util:config_util",
#],
#)

cpplint()
